version: "3.7"

services:
  web:
    image: 2hog/docker-training-samples-micro-sinatra
    init: true
    deploy:
      replicas: 1
    secrets:
      - auth_user
      - auth_password

secrets:
  auth_user:
    external: true
    name: micro-sinatra-auth-user

  auth_password:
    external: true
    name: micro-sinatra-auth-password
