apiVersion: v1
kind: Service
metadata:
  name: docker-training-samples-micro-sinatra
spec:
  type: NodePort
  selector:
    app: docker-training-samples-micro-sinatra
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
